[build]
builder = "NIXPACKS"

[build.nixpacks]
providers = ["python"]

[deploy]
startCommand = "gunicorn main:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[[services]]
protocol = "http"
name = "backend"
